apiVersion: v1
kind: Service
metadata:
  name: monitoring-server-nodeport-service
spec:
    type: NodePort
    ports:
      - name: "http-port"
        protocol: "TCP"
        port: 8080
        targetPort: 8080
        nodePort: 30080
    selector:
        app: app

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-server-cluster-ip-service
spec:
    type: ClusterIP
    ports:
      - name: "http-port"
        protocol: "TCP"
        port: 8080
        targetPort: 8080
    selector:
        app: app
